[workspace]
    resolver = "2"
    members  = ["oxylc","oxylc-fuzzer"]

    [workspace.package]
        authors = ["Ian Pratt <ianjdpratt@gmail.com>"]
        edition = "2024"
        license = "MIT"
