[workspace]
    resolver        = "3"
    members         = ["oxylc", "oxylc-fuzzer"]
    default-members = ["oxylc"]

    [workspace.package]
        authors = ["Ian Pratt <ianjdpratt@gmail.com>"]
        edition = "2024"
        license = "MIT"
